/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DataSharingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCreditor(address,bytes32,string,string,string,string,string)"
      | "addCreditor(bytes32,address)"
      | "addDebtor"
      | "addDebtorToCreditor"
      | "delegate"
      | "eip712Domain"
      | "executeMetaTransaction"
      | "getActiveCreditorsByStatus"
      | "getCreditor"
      | "getDebtor"
      | "getDebtorDataActiveCreditors"
      | "getStatusRequest"
      | "nonces"
      | "owner"
      | "purchasePackage"
      | "removeCreditor"
      | "removeDebtor"
      | "renounceOwnership"
      | "requestDelegation(bytes32,bytes32,bytes32)"
      | "requestDelegation(bytes32,bytes32,bytes32,string,string,string,string)"
      | "setPlatform"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreditorAddedWithMetadata"
      | "DebtorAddedWithMetadata"
      | "Delegate"
      | "DelegationRequestedMetadata"
      | "EIP712DomainChanged"
      | "MetaTransactionExecuted"
      | "OwnershipTransferred"
      | "PackagePurchased"
      | "SetNewAddressPlatform"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCreditor(address,bytes32,string,string,string,string,string)",
    values: [AddressLike, BytesLike, string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addCreditor(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDebtor",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDebtorToCreditor",
    values: [
      BytesLike,
      BytesLike,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "delegate",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeMetaTransaction",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCreditorsByStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebtor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebtorDataActiveCreditors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatusRequest",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchasePackage",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCreditor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDebtor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDelegation(bytes32,bytes32,bytes32)",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDelegation(bytes32,bytes32,bytes32,string,string,string,string)",
    values: [BytesLike, BytesLike, BytesLike, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatform",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCreditor(address,bytes32,string,string,string,string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCreditor(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addDebtor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDebtorToCreditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMetaTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCreditorsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDebtor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDebtorDataActiveCreditors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatusRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchasePackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCreditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDebtor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDelegation(bytes32,bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDelegation(bytes32,bytes32,bytes32,string,string,string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CreditorAddedWithMetadataEvent {
  export type InputTuple = [
    creditorCode: BytesLike,
    institutionCode: string,
    institutionName: string,
    approvalDate: string,
    signerName: string,
    signerPosition: string
  ];
  export type OutputTuple = [
    creditorCode: string,
    institutionCode: string,
    institutionName: string,
    approvalDate: string,
    signerName: string,
    signerPosition: string
  ];
  export interface OutputObject {
    creditorCode: string;
    institutionCode: string;
    institutionName: string;
    approvalDate: string;
    signerName: string;
    signerPosition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebtorAddedWithMetadataEvent {
  export type InputTuple = [
    nik: BytesLike,
    name: string,
    creditorCode: BytesLike,
    creditorName: string,
    applicationDate: string,
    approvalDate: string,
    urlKTP: string,
    urlApproval: string
  ];
  export type OutputTuple = [
    nik: string,
    name: string,
    creditorCode: string,
    creditorName: string,
    applicationDate: string,
    approvalDate: string,
    urlKTP: string,
    urlApproval: string
  ];
  export interface OutputObject {
    nik: string;
    name: string;
    creditorCode: string;
    creditorName: string;
    applicationDate: string;
    approvalDate: string;
    urlKTP: string;
    urlApproval: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegateEvent {
  export type InputTuple = [
    nik: BytesLike,
    creditorConsumerCode: BytesLike,
    creditorProviderCode: BytesLike,
    status: BigNumberish
  ];
  export type OutputTuple = [
    nik: string,
    creditorConsumerCode: string,
    creditorProviderCode: string,
    status: bigint
  ];
  export interface OutputObject {
    nik: string;
    creditorConsumerCode: string;
    creditorProviderCode: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegationRequestedMetadataEvent {
  export type InputTuple = [
    nik: BytesLike,
    requestId: string,
    creditorConsumerCode: BytesLike,
    creditorProviderCode: BytesLike,
    transactionId: string,
    referenceId: string,
    requestDate: string
  ];
  export type OutputTuple = [
    nik: string,
    requestId: string,
    creditorConsumerCode: string,
    creditorProviderCode: string,
    transactionId: string,
    referenceId: string,
    requestDate: string
  ];
  export interface OutputObject {
    nik: string;
    requestId: string;
    creditorConsumerCode: string;
    creditorProviderCode: string;
    transactionId: string;
    referenceId: string;
    requestDate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetaTransactionExecutedEvent {
  export type InputTuple = [user: AddressLike, functionCall: BytesLike];
  export type OutputTuple = [user: string, functionCall: string];
  export interface OutputObject {
    user: string;
    functionCall: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackagePurchasedEvent {
  export type InputTuple = [
    institutionCode: string,
    purchaseDate: string,
    invoiceNumber: string,
    packageId: BigNumberish,
    quantity: BigNumberish,
    startDate: string,
    endDate: string,
    quota: BigNumberish
  ];
  export type OutputTuple = [
    institutionCode: string,
    purchaseDate: string,
    invoiceNumber: string,
    packageId: bigint,
    quantity: bigint,
    startDate: string,
    endDate: string,
    quota: bigint
  ];
  export interface OutputObject {
    institutionCode: string;
    purchaseDate: string;
    invoiceNumber: string;
    packageId: bigint;
    quantity: bigint;
    startDate: string;
    endDate: string;
    quota: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetNewAddressPlatformEvent {
  export type InputTuple = [platform: AddressLike];
  export type OutputTuple = [platform: string];
  export interface OutputObject {
    platform: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataSharing extends BaseContract {
  connect(runner?: ContractRunner | null): DataSharing;
  waitForDeployment(): Promise<this>;

  interface: DataSharingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "addCreditor(address,bytes32,string,string,string,string,string)": TypedContractMethod<
    [
      creditorAddress: AddressLike,
      creditorCode: BytesLike,
      institutionCode: string,
      institutionName: string,
      approvalDate: string,
      signerName: string,
      signerPosition: string
    ],
    [void],
    "nonpayable"
  >;

  "addCreditor(bytes32,address)": TypedContractMethod<
    [creditorCode: BytesLike, creditorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  addDebtor: TypedContractMethod<
    [nik: BytesLike, debtorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  addDebtorToCreditor: TypedContractMethod<
    [
      nik: BytesLike,
      creditor: BytesLike,
      name: string,
      creditorName: string,
      applicationDate: string,
      approvalDate: string,
      urlKTP: string,
      urlApproval: string
    ],
    [void],
    "nonpayable"
  >;

  delegate: TypedContractMethod<
    [
      nik: BytesLike,
      consumer: BytesLike,
      provider: BytesLike,
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  executeMetaTransaction: TypedContractMethod<
    [
      from: AddressLike,
      nonce: BigNumberish,
      functionCall: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getActiveCreditorsByStatus: TypedContractMethod<
    [nik: BytesLike, status: BigNumberish],
    [string[]],
    "view"
  >;

  getCreditor: TypedContractMethod<[codeCreditor: BytesLike], [string], "view">;

  getDebtor: TypedContractMethod<[nik: BytesLike], [string], "view">;

  getDebtorDataActiveCreditors: TypedContractMethod<
    [nik: BytesLike],
    [[string[], bigint[]]],
    "view"
  >;

  getStatusRequest: TypedContractMethod<
    [nik: BytesLike, creditor: BytesLike],
    [bigint],
    "view"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  purchasePackage: TypedContractMethod<
    [
      institutionCode: string,
      purchaseDate: string,
      invoiceNumber: string,
      packageId: BigNumberish,
      quantity: BigNumberish,
      startDate: string,
      endDate: string,
      quota: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  removeCreditor: TypedContractMethod<
    [creditorCode: BytesLike],
    [void],
    "nonpayable"
  >;

  removeDebtor: TypedContractMethod<[nik: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "requestDelegation(bytes32,bytes32,bytes32)": TypedContractMethod<
    [nik: BytesLike, consumer: BytesLike, provider: BytesLike],
    [void],
    "nonpayable"
  >;

  "requestDelegation(bytes32,bytes32,bytes32,string,string,string,string)": TypedContractMethod<
    [
      nik: BytesLike,
      consumer: BytesLike,
      provider: BytesLike,
      requestId: string,
      transactionId: string,
      referenceId: string,
      requestDate: string
    ],
    [void],
    "nonpayable"
  >;

  setPlatform: TypedContractMethod<
    [setNewPlatform: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCreditor(address,bytes32,string,string,string,string,string)"
  ): TypedContractMethod<
    [
      creditorAddress: AddressLike,
      creditorCode: BytesLike,
      institutionCode: string,
      institutionName: string,
      approvalDate: string,
      signerName: string,
      signerPosition: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addCreditor(bytes32,address)"
  ): TypedContractMethod<
    [creditorCode: BytesLike, creditorAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addDebtor"
  ): TypedContractMethod<
    [nik: BytesLike, debtorAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addDebtorToCreditor"
  ): TypedContractMethod<
    [
      nik: BytesLike,
      creditor: BytesLike,
      name: string,
      creditorName: string,
      applicationDate: string,
      approvalDate: string,
      urlKTP: string,
      urlApproval: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegate"
  ): TypedContractMethod<
    [
      nik: BytesLike,
      consumer: BytesLike,
      provider: BytesLike,
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeMetaTransaction"
  ): TypedContractMethod<
    [
      from: AddressLike,
      nonce: BigNumberish,
      functionCall: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveCreditorsByStatus"
  ): TypedContractMethod<
    [nik: BytesLike, status: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreditor"
  ): TypedContractMethod<[codeCreditor: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDebtor"
  ): TypedContractMethod<[nik: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDebtorDataActiveCreditors"
  ): TypedContractMethod<[nik: BytesLike], [[string[], bigint[]]], "view">;
  getFunction(
    nameOrSignature: "getStatusRequest"
  ): TypedContractMethod<
    [nik: BytesLike, creditor: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchasePackage"
  ): TypedContractMethod<
    [
      institutionCode: string,
      purchaseDate: string,
      invoiceNumber: string,
      packageId: BigNumberish,
      quantity: BigNumberish,
      startDate: string,
      endDate: string,
      quota: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeCreditor"
  ): TypedContractMethod<[creditorCode: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDebtor"
  ): TypedContractMethod<[nik: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDelegation(bytes32,bytes32,bytes32)"
  ): TypedContractMethod<
    [nik: BytesLike, consumer: BytesLike, provider: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestDelegation(bytes32,bytes32,bytes32,string,string,string,string)"
  ): TypedContractMethod<
    [
      nik: BytesLike,
      consumer: BytesLike,
      provider: BytesLike,
      requestId: string,
      transactionId: string,
      referenceId: string,
      requestDate: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatform"
  ): TypedContractMethod<[setNewPlatform: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CreditorAddedWithMetadata"
  ): TypedContractEvent<
    CreditorAddedWithMetadataEvent.InputTuple,
    CreditorAddedWithMetadataEvent.OutputTuple,
    CreditorAddedWithMetadataEvent.OutputObject
  >;
  getEvent(
    key: "DebtorAddedWithMetadata"
  ): TypedContractEvent<
    DebtorAddedWithMetadataEvent.InputTuple,
    DebtorAddedWithMetadataEvent.OutputTuple,
    DebtorAddedWithMetadataEvent.OutputObject
  >;
  getEvent(
    key: "Delegate"
  ): TypedContractEvent<
    DelegateEvent.InputTuple,
    DelegateEvent.OutputTuple,
    DelegateEvent.OutputObject
  >;
  getEvent(
    key: "DelegationRequestedMetadata"
  ): TypedContractEvent<
    DelegationRequestedMetadataEvent.InputTuple,
    DelegationRequestedMetadataEvent.OutputTuple,
    DelegationRequestedMetadataEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "MetaTransactionExecuted"
  ): TypedContractEvent<
    MetaTransactionExecutedEvent.InputTuple,
    MetaTransactionExecutedEvent.OutputTuple,
    MetaTransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PackagePurchased"
  ): TypedContractEvent<
    PackagePurchasedEvent.InputTuple,
    PackagePurchasedEvent.OutputTuple,
    PackagePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "SetNewAddressPlatform"
  ): TypedContractEvent<
    SetNewAddressPlatformEvent.InputTuple,
    SetNewAddressPlatformEvent.OutputTuple,
    SetNewAddressPlatformEvent.OutputObject
  >;

  filters: {
    "CreditorAddedWithMetadata(bytes32,string,string,string,string,string)": TypedContractEvent<
      CreditorAddedWithMetadataEvent.InputTuple,
      CreditorAddedWithMetadataEvent.OutputTuple,
      CreditorAddedWithMetadataEvent.OutputObject
    >;
    CreditorAddedWithMetadata: TypedContractEvent<
      CreditorAddedWithMetadataEvent.InputTuple,
      CreditorAddedWithMetadataEvent.OutputTuple,
      CreditorAddedWithMetadataEvent.OutputObject
    >;

    "DebtorAddedWithMetadata(bytes32,string,bytes32,string,string,string,string,string)": TypedContractEvent<
      DebtorAddedWithMetadataEvent.InputTuple,
      DebtorAddedWithMetadataEvent.OutputTuple,
      DebtorAddedWithMetadataEvent.OutputObject
    >;
    DebtorAddedWithMetadata: TypedContractEvent<
      DebtorAddedWithMetadataEvent.InputTuple,
      DebtorAddedWithMetadataEvent.OutputTuple,
      DebtorAddedWithMetadataEvent.OutputObject
    >;

    "Delegate(bytes32,bytes32,bytes32,uint8)": TypedContractEvent<
      DelegateEvent.InputTuple,
      DelegateEvent.OutputTuple,
      DelegateEvent.OutputObject
    >;
    Delegate: TypedContractEvent<
      DelegateEvent.InputTuple,
      DelegateEvent.OutputTuple,
      DelegateEvent.OutputObject
    >;

    "DelegationRequestedMetadata(bytes32,string,bytes32,bytes32,string,string,string)": TypedContractEvent<
      DelegationRequestedMetadataEvent.InputTuple,
      DelegationRequestedMetadataEvent.OutputTuple,
      DelegationRequestedMetadataEvent.OutputObject
    >;
    DelegationRequestedMetadata: TypedContractEvent<
      DelegationRequestedMetadataEvent.InputTuple,
      DelegationRequestedMetadataEvent.OutputTuple,
      DelegationRequestedMetadataEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "MetaTransactionExecuted(address,bytes)": TypedContractEvent<
      MetaTransactionExecutedEvent.InputTuple,
      MetaTransactionExecutedEvent.OutputTuple,
      MetaTransactionExecutedEvent.OutputObject
    >;
    MetaTransactionExecuted: TypedContractEvent<
      MetaTransactionExecutedEvent.InputTuple,
      MetaTransactionExecutedEvent.OutputTuple,
      MetaTransactionExecutedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PackagePurchased(string,string,string,uint256,uint256,string,string,uint256)": TypedContractEvent<
      PackagePurchasedEvent.InputTuple,
      PackagePurchasedEvent.OutputTuple,
      PackagePurchasedEvent.OutputObject
    >;
    PackagePurchased: TypedContractEvent<
      PackagePurchasedEvent.InputTuple,
      PackagePurchasedEvent.OutputTuple,
      PackagePurchasedEvent.OutputObject
    >;

    "SetNewAddressPlatform(address)": TypedContractEvent<
      SetNewAddressPlatformEvent.InputTuple,
      SetNewAddressPlatformEvent.OutputTuple,
      SetNewAddressPlatformEvent.OutputObject
    >;
    SetNewAddressPlatform: TypedContractEvent<
      SetNewAddressPlatformEvent.InputTuple,
      SetNewAddressPlatformEvent.OutputTuple,
      SetNewAddressPlatformEvent.OutputObject
    >;
  };
}
