/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dataEntrySol from "./DataEntry.sol";
export * as ePentingNewSol from "./EPentingNew.sol";
export { MetaTransaction__factory } from "./MetaTransaction__factory";
export { RBACRegistry__factory } from "./RBACRegistry__factory";
