/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dataEntrySol from "./DataEntry.sol";
export type { dataEntrySol };
import type * as ePentingNewSol from "./EPentingNew.sol";
export type { ePentingNewSol };
export type { MetaTransaction } from "./MetaTransaction";
export type { RBACRegistry } from "./RBACRegistry";
